version: '3.8'

services:
  my-app:
    build: .
    environment:
      - LOGS_ENABLED=true
      - LOGS_APP_NAME=billing-service
      - LOGS_URL=http://loki:3100/loki/api/v1/push
      - LOGS_TENANT=tenant_1

      - LOGS_COMPRESSION=snappy
      - LOGS_USE_WORKERS=true
      - LOGS_BUFFER_MAX_SIZE=2000
      - LOGS_BUFFER_FLUSH_INTERVAL=2000
      - LOGS_BUFFER_MAX_MEMORY_MB=512

      - NODE_OPTIONS=--require logs-interceptor/preload

    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
